apiVersion: v1
kind: Service
metadata:
  name: omsl-emqx-listeners
  namespace: default
spec:
  type: ClusterIP
  selector:
    "apps.emqx.io/instance": omsl-emqx-cluster
    "apps.emqx.io/db-role": replicant
  ports:
    - name: mqtt-tcp
      port: 1883
      targetPort: 1883
    - name: dashboard
      port: 18083
      targetPort: 18083
